# This file is generated by the scaffold script below.
# Replace or extend as you iterate—keep it simple and readable.

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

os.makedirs("reports/tables", exist_ok=True)
os.makedirs("reports/figures", exist_ok=True)

df = pd.read_csv("data/sample/latency.csv", parse_dates=["ts"])
df["minute"] = df["ts"].dt.floor("5min")
grp = df.groupby("minute")["latency_ms"]

summary = pd.DataFrame({
    "p50": grp.quantile(0.5),
    "p95": grp.quantile(0.95),
    "count": grp.count()
}).reset_index()

summary.to_csv("reports/tables/latency_summary.csv", index=False)

plt.figure()
plt.plot(summary["minute"], summary["p95"], marker="o")
plt.title("Latency p95 over time (sample)")
plt.xlabel("time")
plt.ylabel("ms")
plt.tight_layout()
plt.savefig("reports/figures/latency_p95.png", dpi=160)
print("Wrote reports/tables/latency_summary.csv and reports/figures/latency_p95.png")

